name="lan-bigbohne-de"
main="src/index.ts"

compatibility_date = "2023-12-18"

kv_namespaces = [
    { binding = "KV", id = "665bb3a3f4df49469fd4903a9bdbec31" }
]


[limits]
cpu_ms = 50

[site]
bucket = "./assets"

